"""DocAssistIQ — PatientSession and ConsentRecord Models.

PatientSession: represents a de-identified patient encounter record.
Patient-identifiable data is NEVER stored here. The session is scoped
to a tenant and linked to the attending doctor.

ConsentRecord: immutable audit record for a patient's consent to their
data being used in the clinical decision support system.

Clinical safety requirements:
  - No name, DOB, NHS/MRN, postcode, or any other direct identifier.
  - patient_ref is an opaque token generated by the clinical system
    (EMR/HIS), never a real name or ID visible outside that system.
  - Consent records are append-only; revocation creates a new record
    with type='revocation' rather than deleting the prior consent.
"""

from __future__ import annotations

import uuid

from sqlalchemy import ForeignKey, Index, String, Text, UniqueConstraint
from sqlalchemy.dialects.postgresql import UUID as PG_UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.infrastructure.database import Base
from app.infrastructure.models import TimestampMixin, UUIDPrimaryKeyMixin


class PatientSession(UUIDPrimaryKeyMixin, TimestampMixin, Base):
    """
    A de-identified patient encounter record.

    Stores only:
      - An opaque external reference (patient_ref) from the EMR/HIS.
      - Encounter metadata (type, status, timestamps).
      - Tenant and doctor linkage.
    Never stores: name, date of birth, NHS/MRN, postcode, or any
    information that could identify the individual.
    """

    __tablename__ = "patient_sessions"

    __table_args__ = (
        Index("ix_patient_sessions_tenant_doctor", "tenant_id", "doctor_id"),
        Index("ix_patient_sessions_status", "status"),
    )

    tenant_id: Mapped[uuid.UUID] = mapped_column(
        PG_UUID(as_uuid=True),
        ForeignKey("tenants.id", ondelete="RESTRICT"),
        nullable=False,
        index=True,
        comment="Owning tenant",
    )

    doctor_id: Mapped[uuid.UUID] = mapped_column(
        PG_UUID(as_uuid=True),
        ForeignKey("doctors.id", ondelete="RESTRICT"),
        nullable=False,
        index=True,
        comment="Attending doctor (FK to doctors, not users)",
    )

    patient_ref: Mapped[str] = mapped_column(
        String(200),
        nullable=False,
        comment=(
            "Opaque external reference from EMR/HIS. "
            "NOT a real name, NHS number, or any direct identifier."
        ),
    )

    encounter_type: Mapped[str] = mapped_column(
        String(60),
        nullable=False,
        server_default="outpatient",
        comment="'inpatient' | 'outpatient' | 'emergency' | 'telemedicine'",
    )

    status: Mapped[str] = mapped_column(
        String(20),
        nullable=False,
        server_default="open",
        comment="Lifecycle: 'open' | 'closed' | 'archived'",
    )

    clinical_notes_summary: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
        comment="Non-identifying encounter summary (no PII)",
    )

    def __repr__(self) -> str:
        return f"<PatientSession id={self.id} status={self.status!r}>"


class ConsentRecord(UUIDPrimaryKeyMixin, TimestampMixin, Base):
    """
    Immutable audit trail for patient consent.

    Append-only: revocations are new records (type='revocation'),
    not deletions. This preserves the full consent history.
    """

    __tablename__ = "consent_records"

    __table_args__ = (
        Index("ix_consent_records_session", "patient_session_id"),
    )

    patient_session_id: Mapped[uuid.UUID] = mapped_column(
        PG_UUID(as_uuid=True),
        ForeignKey("patient_sessions.id", ondelete="RESTRICT"),
        nullable=False,
        comment="Related patient session",
    )

    tenant_id: Mapped[uuid.UUID] = mapped_column(
        PG_UUID(as_uuid=True),
        ForeignKey("tenants.id", ondelete="RESTRICT"),
        nullable=False,
        comment="Tenant scope",
    )

    consent_type: Mapped[str] = mapped_column(
        String(40),
        nullable=False,
        comment="'explicit' | 'implied' | 'revocation'",
    )

    mechanism: Mapped[str] = mapped_column(
        String(60),
        nullable=False,
        comment="How consent was obtained: 'verbal' | 'written' | 'electronic'",
    )

    scope: Mapped[str] = mapped_column(
        Text,
        nullable=False,
        comment="Description of what was consented to (non-PII)",
    )

    recorded_by_id: Mapped[uuid.UUID] = mapped_column(
        PG_UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="RESTRICT"),
        nullable=False,
        comment="Clinician who recorded this consent",
    )

    def __repr__(self) -> str:
        return f"<ConsentRecord id={self.id} type={self.consent_type!r}>"
