from app.schemas.investigation import InvestigationResponse, InvestigationSuggestion
from sqlalchemy.ext.asyncio import AsyncSession
from app.services.rag_service import retrieve_medical_context
from app.services.llm_service import llm_service
import structlog

log = structlog.get_logger(__name__)

class InvestigationProvider:
    """
    Provides clinician-facing reference intelligence for investigations based on disease (Phase 44).
    This serves strictly as reference intelligence and NOT as an automated order system.
    """

    async def get_investigations(self, db: AsyncSession, disease_name: str, representation: "ClinicalRepresentationResponse", competing: list[str] = None) -> InvestigationResponse:
        """
        Returns reference investigations for the specified disease dynamically generated by LLM, tailored to the patient context.
        """
        competing = competing or []
        
        # 1. Base RAG Context
        rag_context = await retrieve_medical_context(db, f"{disease_name} investigations and workup", top_k=3)
        
        # 2. Live Wikipedia Fetch (Gold Standard Diagnosis Data)
        try:
            import httpx
            from urllib.parse import quote
            async with httpx.AsyncClient(timeout=3.0) as client:
                wiki_res = await client.get(f"https://en.wikipedia.org/api/rest_v1/page/summary/{quote(disease_name)}")
                if wiki_res.status_code == 200:
                    wiki_data = wiki_res.json()
                    live_text = wiki_data.get("extract", "")
                    if live_text:
                        rag_context = f"LIVE WIKIPEDIA DIAGNOSIS SUMMARY:\n{live_text}\n\nSTATIC RAG CONTEXT:\n{rag_context}"
        except Exception as e:
            log.error("live_wikipedia_fetch_failed", error=str(e))
        
        # 3. Build patient context
        symptoms = ", ".join([item.value for item in representation.symptoms]) if representation.symptoms else "None reported"
        vitals = ", ".join([item.value for item in representation.vitals]) if representation.vitals else "None reported"
        history = ", ".join([item.value for item in representation.history]) if representation.history else "None reported"
        
        competing_str = ", ".join(competing) if competing else "None"
        
        patient_context = f"Symptoms: {symptoms}\\nVitals: {vitals}\\nHistory: {history}\\nCompeting Differentials to Rule Out: {competing_str}"

        system_prompt = f"""You are an Expert Pathologist and Radiologist AI.
Your task is to recommend a COMPREHENSIVE, specific, and highly accurate clinical workup (lab tests, imaging, specialist referrals) to confirm or rule out the disease: '{disease_name}'.
You must tailor these investigations to the specific Patient Context provided.
CRITICAL INSTRUCTION: If "Competing Differentials to Rule Out" are provided, you MUST specifically include tests that help differentiate '{disease_name}' from those competing diseases (e.g., specific serology, cultures, or imaging).
CRITICAL INSTRUCTION: You MUST output standardized, specific medical test names (e.g. "Complete Blood Count (CBC) with differential", "Dengue NS1 Antigen", "CT Abdomen/Pelvis with IV contrast") rather than generic terms.
You MUST ground your response in the retrieved medical data (including live Wikipedia data).

## Patient Context:
{patient_context}

## Retrieved Context:
{rag_context}

Return ONLY valid JSON matching this exact schema:
{{
  "suggestions": [
    {{
      "name": "string (Specific, standardized medical name of investigation)",
      "priority": "string (HIGH PRIORITY, CONDITIONAL, or IF INDICATED)",
      "rationale": "string (specifically why this test is needed for THIS patient, and if applicable, how it rules out competing differentials)",
      "relevant_clinical_finding": "string (symptoms prompting this test)",
      "evidence": "string (guideline or evidence reference)",
      "limitations": "string (limitations of the test)",
      "safety_flags": ["string"],
      "provenance": "string"
    }}
  ]
}}"""
        
        try:
            user_prompt = "Generate a comprehensive list of at least 3-5 investigation suggestions based on the context."
            data = await llm_service.generate_json(user_prompt, system=system_prompt)
            
            suggestions = []
            for item in data.get("suggestions", []):
                suggestions.append(InvestigationSuggestion(**item))
                
            return InvestigationResponse(disease=disease_name, suggestions=suggestions)
        except Exception as e:
            log.error("llm_investigation_failed", error=str(e))
            return InvestigationResponse(disease=disease_name, suggestions=[])

investigation_provider = InvestigationProvider()
