"""Add KnowledgeVersioningMixin fields

Revision ID: 016062e36592
Revises: 11e261372f47
Create Date: 2026-09-06 18:12:35.635468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '016062e36592'
down_revision: Union[str, None] = '11e261372f47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diseases', sa.Column('publication_date', sa.String(length=20), nullable=True, comment='Original publication date of the source'))
    op.add_column('diseases', sa.Column('retrieval_date', sa.String(length=40), nullable=True, comment='When it was ingested'))
    op.add_column('diseases', sa.Column('effective_date', sa.String(length=40), nullable=True, comment='When this became active in production'))
    op.add_column('diseases', sa.Column('version_string', sa.String(length=40), nullable=True, comment='Semantic version or source version'))
    op.add_column('diseases', sa.Column('content_hash', sa.String(length=64), nullable=True, comment='Hash of the core content to detect mutations'))
    op.add_column('diseases', sa.Column('credibility_tier', sa.String(length=20), server_default='unknown', nullable=False, comment="'primary' | 'secondary' | 'tertiary' | 'unknown'"))
    op.add_column('diseases', sa.Column('evidence_level', sa.String(length=10), nullable=True, comment="Highest level of evidence (e.g. 'Ia')"))
    op.add_column('diseases', sa.Column('superseded_by_id', sa.UUID(), nullable=True, comment='FK to the entity that superseded this one'))
    op.add_column('investigations', sa.Column('publication_date', sa.String(length=20), nullable=True, comment='Original publication date of the source'))
    op.add_column('investigations', sa.Column('retrieval_date', sa.String(length=40), nullable=True, comment='When it was ingested'))
    op.add_column('investigations', sa.Column('effective_date', sa.String(length=40), nullable=True, comment='When this became active in production'))
    op.add_column('investigations', sa.Column('version_string', sa.String(length=40), nullable=True, comment='Semantic version or source version'))
    op.add_column('investigations', sa.Column('content_hash', sa.String(length=64), nullable=True, comment='Hash of the core content to detect mutations'))
    op.add_column('investigations', sa.Column('credibility_tier', sa.String(length=20), server_default='unknown', nullable=False, comment="'primary' | 'secondary' | 'tertiary' | 'unknown'"))
    op.add_column('investigations', sa.Column('evidence_level', sa.String(length=10), nullable=True, comment="Highest level of evidence (e.g. 'Ia')"))
    op.add_column('investigations', sa.Column('superseded_by_id', sa.UUID(), nullable=True, comment='FK to the entity that superseded this one'))
    op.add_column('medicines', sa.Column('publication_date', sa.String(length=20), nullable=True, comment='Original publication date of the source'))
    op.add_column('medicines', sa.Column('retrieval_date', sa.String(length=40), nullable=True, comment='When it was ingested'))
    op.add_column('medicines', sa.Column('effective_date', sa.String(length=40), nullable=True, comment='When this became active in production'))
    op.add_column('medicines', sa.Column('version_string', sa.String(length=40), nullable=True, comment='Semantic version or source version'))
    op.add_column('medicines', sa.Column('content_hash', sa.String(length=64), nullable=True, comment='Hash of the core content to detect mutations'))
    op.add_column('medicines', sa.Column('credibility_tier', sa.String(length=20), server_default='unknown', nullable=False, comment="'primary' | 'secondary' | 'tertiary' | 'unknown'"))
    op.add_column('medicines', sa.Column('evidence_level', sa.String(length=10), nullable=True, comment="Highest level of evidence (e.g. 'Ia')"))
    op.add_column('medicines', sa.Column('superseded_by_id', sa.UUID(), nullable=True, comment='FK to the entity that superseded this one'))
    op.add_column('symptoms', sa.Column('publication_date', sa.String(length=20), nullable=True, comment='Original publication date of the source'))
    op.add_column('symptoms', sa.Column('retrieval_date', sa.String(length=40), nullable=True, comment='When it was ingested'))
    op.add_column('symptoms', sa.Column('effective_date', sa.String(length=40), nullable=True, comment='When this became active in production'))
    op.add_column('symptoms', sa.Column('version_string', sa.String(length=40), nullable=True, comment='Semantic version or source version'))
    op.add_column('symptoms', sa.Column('content_hash', sa.String(length=64), nullable=True, comment='Hash of the core content to detect mutations'))
    op.add_column('symptoms', sa.Column('credibility_tier', sa.String(length=20), server_default='unknown', nullable=False, comment="'primary' | 'secondary' | 'tertiary' | 'unknown'"))
    op.add_column('symptoms', sa.Column('evidence_level', sa.String(length=10), nullable=True, comment="Highest level of evidence (e.g. 'Ia')"))
    op.add_column('symptoms', sa.Column('superseded_by_id', sa.UUID(), nullable=True, comment='FK to the entity that superseded this one'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('symptoms', 'superseded_by_id')
    op.drop_column('symptoms', 'evidence_level')
    op.drop_column('symptoms', 'credibility_tier')
    op.drop_column('symptoms', 'content_hash')
    op.drop_column('symptoms', 'version_string')
    op.drop_column('symptoms', 'effective_date')
    op.drop_column('symptoms', 'retrieval_date')
    op.drop_column('symptoms', 'publication_date')
    op.drop_column('medicines', 'superseded_by_id')
    op.drop_column('medicines', 'evidence_level')
    op.drop_column('medicines', 'credibility_tier')
    op.drop_column('medicines', 'content_hash')
    op.drop_column('medicines', 'version_string')
    op.drop_column('medicines', 'effective_date')
    op.drop_column('medicines', 'retrieval_date')
    op.drop_column('medicines', 'publication_date')
    op.drop_column('investigations', 'superseded_by_id')
    op.drop_column('investigations', 'evidence_level')
    op.drop_column('investigations', 'credibility_tier')
    op.drop_column('investigations', 'content_hash')
    op.drop_column('investigations', 'version_string')
    op.drop_column('investigations', 'effective_date')
    op.drop_column('investigations', 'retrieval_date')
    op.drop_column('investigations', 'publication_date')
    op.drop_column('diseases', 'superseded_by_id')
    op.drop_column('diseases', 'evidence_level')
    op.drop_column('diseases', 'credibility_tier')
    op.drop_column('diseases', 'content_hash')
    op.drop_column('diseases', 'version_string')
    op.drop_column('diseases', 'effective_date')
    op.drop_column('diseases', 'retrieval_date')
    op.drop_column('diseases', 'retrieval_date')
    op.drop_column('diseases', 'publication_date')
    # ### end Alembic commands ###
