"""Update knowledge status defaults

Revision ID: 11e261372f47
Revises: 285f563fee18
Create Date: 2026-09-06 18:01:52.318122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11e261372f47'
down_revision: Union[str, None] = '285f563fee18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('diseases', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default='PENDING_REVIEW',
               comment="'PENDING_REVIEW' | 'APPROVED' | 'REJECTED' | 'SUPERSEDED' | 'OUTDATED'",
               existing_comment="'draft' | 'verified' | 'deprecated'",
               existing_nullable=False)
    op.alter_column('investigations', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default='PENDING_REVIEW',
               comment="'PENDING_REVIEW' | 'APPROVED' | 'REJECTED' | 'SUPERSEDED' | 'OUTDATED'",
               existing_comment="'draft' | 'verified' | 'deprecated'",
               existing_nullable=False)
    op.alter_column('medicines', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default='PENDING_REVIEW',
               comment="'PENDING_REVIEW' | 'APPROVED' | 'REJECTED' | 'SUPERSEDED' | 'OUTDATED'",
               existing_comment="'draft' | 'verified' | 'deprecated'",
               existing_nullable=False)
    op.alter_column('symptoms', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default='PENDING_REVIEW',
               comment="'PENDING_REVIEW' | 'APPROVED' | 'REJECTED' | 'SUPERSEDED' | 'OUTDATED'",
               existing_comment="'draft' | 'verified' | 'deprecated'",
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('symptoms', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'draft'::character varying"),
               comment="'draft' | 'verified' | 'deprecated'",
               existing_comment="'PENDING_REVIEW' | 'APPROVED' | 'REJECTED' | 'SUPERSEDED' | 'OUTDATED'",
               existing_nullable=False)
    op.alter_column('medicines', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'draft'::character varying"),
               comment="'draft' | 'verified' | 'deprecated'",
               existing_comment="'PENDING_REVIEW' | 'APPROVED' | 'REJECTED' | 'SUPERSEDED' | 'OUTDATED'",
               existing_nullable=False)
    op.alter_column('investigations', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'draft'::character varying"),
               comment="'draft' | 'verified' | 'deprecated'",
               existing_comment="'PENDING_REVIEW' | 'APPROVED' | 'REJECTED' | 'SUPERSEDED' | 'OUTDATED'",
               existing_nullable=False)
    op.alter_column('diseases', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'draft'::character varying"),
               comment="'draft' | 'verified' | 'deprecated'",
               existing_comment="'PENDING_REVIEW' | 'APPROVED' | 'REJECTED' | 'SUPERSEDED' | 'OUTDATED'",
               existing_nullable=False)
    # ### end Alembic commands ###
