"""Add PostBookmark and specialty_tags to DoctorPost

Revision ID: 12755713377a
Revises: 76345eb58c0c
Create Date: 2026-09-11 22:34:03.293160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '12755713377a'
down_revision: Union[str, None] = '76345eb58c0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor_posts', sa.Column('specialty_tags', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    
    op.create_table('post_bookmarks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['doctor_posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'doctor_id', name='uq_post_bookmark_doctor')
    )
    op.create_index(op.f('ix_post_bookmarks_doctor_id'), 'post_bookmarks', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_post_bookmarks_post_id'), 'post_bookmarks', ['post_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_bookmarks_post_id'), table_name='post_bookmarks')
    op.drop_index(op.f('ix_post_bookmarks_doctor_id'), table_name='post_bookmarks')
    op.drop_table('post_bookmarks')
    op.drop_column('doctor_posts', 'specialty_tags')
    # ### end Alembic commands ###
