"""Add tenant_id to core clinical models

Revision ID: 163d47bee688
Revises: 0baf3521f402
Create Date: 2026-09-12 11:46:44.381532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = '163d47bee688'
down_revision: Union[str, None] = '0baf3521f402'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Clear clinical tables before adding NOT NULL tenant_id
    op.execute("TRUNCATE TABLE clinical_findings, clinical_notes, consent_records, consultations, manual_intakes, transcript_segments, transcripts CASCADE")
    op.add_column('clinical_findings', sa.Column('tenant_id', sa.Uuid(), nullable=False, comment='The tenant this data belongs to'))
    op.create_index(op.f('ix_clinical_findings_tenant_id'), 'clinical_findings', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'clinical_findings', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.add_column('clinical_notes', sa.Column('tenant_id', sa.Uuid(), nullable=False, comment='The tenant this data belongs to'))
    op.create_index(op.f('ix_clinical_notes_tenant_id'), 'clinical_notes', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'clinical_notes', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.add_column('consent_records', sa.Column('tenant_id', sa.Uuid(), nullable=False, comment='The tenant this data belongs to'))
    op.create_index(op.f('ix_consent_records_tenant_id'), 'consent_records', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'consent_records', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.add_column('consultations', sa.Column('tenant_id', sa.Uuid(), nullable=False, comment='The tenant this data belongs to'))
    op.create_index(op.f('ix_consultations_tenant_id'), 'consultations', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'consultations', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.add_column('manual_intakes', sa.Column('tenant_id', sa.Uuid(), nullable=False, comment='The tenant this data belongs to'))
    op.create_index(op.f('ix_manual_intakes_tenant_id'), 'manual_intakes', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'manual_intakes', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.add_column('transcript_segments', sa.Column('tenant_id', sa.Uuid(), nullable=False, comment='The tenant this data belongs to'))
    op.create_index(op.f('ix_transcript_segments_tenant_id'), 'transcript_segments', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'transcript_segments', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.add_column('transcripts', sa.Column('tenant_id', sa.Uuid(), nullable=False, comment='The tenant this data belongs to'))
    op.create_index(op.f('ix_transcripts_tenant_id'), 'transcripts', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'transcripts', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transcripts', type_='foreignkey')
    op.drop_index(op.f('ix_transcripts_tenant_id'), table_name='transcripts')
    op.drop_column('transcripts', 'tenant_id')
    op.drop_constraint(None, 'transcript_segments', type_='foreignkey')
    op.drop_index(op.f('ix_transcript_segments_tenant_id'), table_name='transcript_segments')
    op.drop_column('transcript_segments', 'tenant_id')
    op.drop_constraint(None, 'manual_intakes', type_='foreignkey')
    op.drop_index(op.f('ix_manual_intakes_tenant_id'), table_name='manual_intakes')
    op.drop_column('manual_intakes', 'tenant_id')
    op.drop_constraint(None, 'consultations', type_='foreignkey')
    op.drop_index(op.f('ix_consultations_tenant_id'), table_name='consultations')
    op.drop_column('consultations', 'tenant_id')
    op.drop_constraint(None, 'consent_records', type_='foreignkey')
    op.drop_index(op.f('ix_consent_records_tenant_id'), table_name='consent_records')
    op.drop_column('consent_records', 'tenant_id')
    op.drop_constraint(None, 'clinical_notes', type_='foreignkey')
    op.drop_index(op.f('ix_clinical_notes_tenant_id'), table_name='clinical_notes')
    op.drop_column('clinical_notes', 'tenant_id')
    op.drop_constraint(None, 'clinical_findings', type_='foreignkey')
    op.drop_index(op.f('ix_clinical_findings_tenant_id'), table_name='clinical_findings')
    op.drop_column('clinical_findings', 'tenant_id')
    # ### end Alembic commands ###
