"""Add IngestionJob table

Revision ID: 285f563fee18
Revises: 06df40b8a7dd
Create Date: 2026-09-06 17:49:56.054584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '285f563fee18'
down_revision: Union[str, None] = '06df40b8a7dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestion_jobs',
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('source_version', sa.String(length=100), nullable=True, comment='Version string from the source (e.g. 2026AA)'),
    sa.Column('status', sa.String(length=40), server_default='pending', nullable=False, comment="'pending' | 'fetching' | 'parsing' | 'validating' | 'completed' | 'failed'"),
    sa.Column('content_hash', sa.String(length=64), nullable=True, comment='SHA-256 hash of the retrieved raw artifact'),
    sa.Column('raw_artifact_url', sa.String(length=1024), nullable=True, comment='Reference to object storage (e.g. MinIO key)'),
    sa.Column('validation_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='JSON output of validation stage (errors, warnings)'),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('review_status', sa.String(length=40), server_default='unreviewed', nullable=False, comment="'unreviewed' | 'approved' | 'rejected'"),
    sa.Column('id', sa.Uuid(), nullable=False, comment='Primary key (UUID v4, generated at INSERT)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Row insertion timestamp (UTC, server-set)'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Last modification timestamp (UTC, server-set)'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ingestion_jobs_source', 'ingestion_jobs', ['source_id'], unique=False)
    op.create_index(op.f('ix_ingestion_jobs_source_id'), 'ingestion_jobs', ['source_id'], unique=False)
    op.create_index('ix_ingestion_jobs_status', 'ingestion_jobs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ingestion_jobs_status', table_name='ingestion_jobs')
    op.drop_index(op.f('ix_ingestion_jobs_source_id'), table_name='ingestion_jobs')
    op.drop_index('ix_ingestion_jobs_source', table_name='ingestion_jobs')
    op.drop_table('ingestion_jobs')
    # ### end Alembic commands ###
