"""Transcript Phase 27

Revision ID: 443f6965dad6
Revises: 4ace63fe03f9
Create Date: 2026-09-06 22:46:16.978627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '443f6965dad6'
down_revision: Union[str, None] = '4ace63fe03f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transcripts',
    sa.Column('consultation_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=30), server_default='recording', nullable=False, comment="'recording', 'processing', 'ready', 'finalized'"),
    sa.Column('id', sa.Uuid(), nullable=False, comment='Primary key (UUID v4, generated at INSERT)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Row insertion timestamp (UTC, server-set)'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Last modification timestamp (UTC, server-set)'),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_transcripts_consultation', 'transcripts', ['consultation_id'], unique=True)
    op.create_table('transcript_segments',
    sa.Column('transcript_id', sa.UUID(), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.Column('speaker_label', sa.String(length=50), nullable=True),
    sa.Column('speaker_confidence', sa.Float(), nullable=True),
    sa.Column('speaker_source', sa.String(length=30), nullable=True, comment="'asr', 'heuristic', 'clinician'"),
    sa.Column('raw_text', sa.Text(), nullable=False, comment='Immutable original ASR output'),
    sa.Column('processed_text', sa.Text(), nullable=False, comment='Cleaned/formatted output'),
    sa.Column('clinician_corrected_text', sa.Text(), nullable=True, comment='Explicit correction'),
    sa.Column('is_corrected', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False, comment='Primary key (UUID v4, generated at INSERT)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Row insertion timestamp (UTC, server-set)'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Last modification timestamp (UTC, server-set)'),
    sa.ForeignKeyConstraint(['transcript_id'], ['transcripts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_transcript_segments_transcript', 'transcript_segments', ['transcript_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transcript_segments_transcript', table_name='transcript_segments')
    op.drop_table('transcript_segments')
    op.drop_index('ix_transcripts_consultation', table_name='transcripts')
    op.drop_table('transcripts')
    # ### end Alembic commands ###
