"""ManualIntake Phase 22

Revision ID: 4ace63fe03f9
Revises: a4b13d9ecfff
Create Date: 2026-09-06 21:42:59.100443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ace63fe03f9'
down_revision: Union[str, None] = 'a4b13d9ecfff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manual_intakes',
    sa.Column('consultation_id', sa.UUID(), nullable=False, comment='Parent consultation'),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='draft', nullable=False, comment="'draft' | 'final' | 'voided'"),
    sa.Column('chief_complaint', sa.Text(), nullable=True),
    sa.Column('symptoms', sa.Text(), nullable=True),
    sa.Column('duration', sa.Text(), nullable=True),
    sa.Column('severity', sa.Text(), nullable=True),
    sa.Column('onset', sa.Text(), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('associated_symptoms', sa.Text(), nullable=True),
    sa.Column('aggravating_factors', sa.Text(), nullable=True),
    sa.Column('relieving_factors', sa.Text(), nullable=True),
    sa.Column('negations', sa.Text(), nullable=True),
    sa.Column('past_medical_history', sa.Text(), nullable=True),
    sa.Column('medications', sa.Text(), nullable=True),
    sa.Column('allergies', sa.Text(), nullable=True),
    sa.Column('family_social_history', sa.Text(), nullable=True),
    sa.Column('vitals', sa.Text(), nullable=True),
    sa.Column('previous_investigations', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False, comment='Primary key (UUID v4, generated at INSERT)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Row insertion timestamp (UTC, server-set)'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Last modification timestamp (UTC, server-set)'),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_manual_intakes_consultation', 'manual_intakes', ['consultation_id'], unique=True)
    op.create_index(op.f('ix_manual_intakes_consultation_id'), 'manual_intakes', ['consultation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_manual_intakes_consultation_id'), table_name='manual_intakes')
    op.drop_index('ix_manual_intakes_consultation', table_name='manual_intakes')
    op.drop_table('manual_intakes')
    # ### end Alembic commands ###
