"""Consultation Phase 20 updates

Revision ID: 5d35b5547965
Revises: bd6d865d81e7
Create Date: 2026-09-06 20:34:49.907985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d35b5547965'
down_revision: Union[str, None] = 'bd6d865d81e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consultation_audits',
    sa.Column('consultation_id', sa.UUID(), nullable=False),
    sa.Column('from_status', sa.String(length=50), nullable=True),
    sa.Column('to_status', sa.String(length=50), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=False, comment='User who triggered the transition'),
    sa.Column('id', sa.Uuid(), nullable=False, comment='Primary key (UUID v4, generated at INSERT)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Row insertion timestamp (UTC, server-set)'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Last modification timestamp (UTC, server-set)'),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consultation_audits_actor_id'), 'consultation_audits', ['actor_id'], unique=False)
    op.create_index(op.f('ix_consultation_audits_consultation_id'), 'consultation_audits', ['consultation_id'], unique=False)
    op.add_column('consultations', sa.Column('doctor_id', sa.UUID(), nullable=False, comment='FK to the submitting doctor'))
    op.add_column('consultations', sa.Column('patient_session_id', sa.UUID(), nullable=True, comment='FK to the patient session'))
    op.alter_column('consultations', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default='created',
               type_=sa.String(length=50),
               comment='Lifecycle: created|recording|processing|draft|under_review|analysis_ready|finalized|amended',
               existing_comment="Lifecycle: 'pending' | 'completed' | 'failed'",
               existing_nullable=False)
    op.drop_index(op.f('ix_consultations_user_created'), table_name='consultations')
    op.drop_index(op.f('ix_consultations_user_id'), table_name='consultations')
    op.create_index('ix_consultations_doctor_created', 'consultations', ['doctor_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_consultations_doctor_id'), 'consultations', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_consultations_patient_session_id'), 'consultations', ['patient_session_id'], unique=False)
    op.drop_constraint(op.f('fk_consultations_user_id'), 'consultations', type_='foreignkey')
    op.create_foreign_key(None, 'consultations', 'doctors', ['doctor_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'consultations', 'patient_sessions', ['patient_session_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('consultations', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consultations', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True, comment='FK to the submitting clinician (cascade delete)'))
    # Drop anonymous FKs on doctor_id and patient_session_id using dynamic SQL
    # (they were created with op.create_foreign_key(None, ...) so names are auto-generated)
    op.execute("""
        DO $$
        DECLARE r RECORD;
        BEGIN
            FOR r IN (
                SELECT tc.constraint_name
                FROM information_schema.table_constraints tc
                JOIN information_schema.constraint_column_usage ccu
                  ON tc.constraint_name = ccu.constraint_name
                WHERE tc.table_name = 'consultations'
                  AND tc.constraint_type = 'FOREIGN KEY'
                  AND ccu.column_name IN ('doctor_id', 'patient_session_id')
            ) LOOP
                EXECUTE 'ALTER TABLE consultations DROP CONSTRAINT IF EXISTS ' || quote_ident(r.constraint_name);
            END LOOP;
        END $$;
    """)
    op.create_foreign_key(op.f('fk_consultations_user_id'), 'consultations', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_consultations_patient_session_id'), table_name='consultations')
    op.drop_index(op.f('ix_consultations_doctor_id'), table_name='consultations')
    op.drop_index('ix_consultations_doctor_created', table_name='consultations')
    op.create_index(op.f('ix_consultations_user_id'), 'consultations', ['user_id'], unique=False)
    op.create_index(op.f('ix_consultations_user_created'), 'consultations', ['user_id', 'created_at'], unique=False)
    op.alter_column('consultations', 'status',
               existing_type=sa.String(length=50),
               server_default=sa.text("'pending'::character varying"),
               type_=sa.VARCHAR(length=20),
               comment="Lifecycle: 'pending' | 'completed' | 'failed'",
               existing_comment='Lifecycle: created|recording|processing|draft|under_review|analysis_ready|finalized|amended',
               existing_nullable=False)
    op.drop_column('consultations', 'patient_session_id')
    op.drop_column('consultations', 'doctor_id')
    op.drop_index(op.f('ix_consultation_audits_consultation_id'), table_name='consultation_audits')
    op.drop_index(op.f('ix_consultation_audits_actor_id'), table_name='consultation_audits')
    op.drop_table('consultation_audits')
    # ### end Alembic commands ###
