"""NLP fields Phase 28

Revision ID: 6a8fe758c63e
Revises: 443f6965dad6
Create Date: 2026-09-06 23:27:25.494644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a8fe758c63e'
down_revision: Union[str, None] = '443f6965dad6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clinical_findings', sa.Column('concept', sa.String(length=100), nullable=True))
    op.add_column('clinical_findings', sa.Column('value', sa.Text(), nullable=True))
    op.add_column('clinical_findings', sa.Column('certainty', sa.String(length=50), nullable=True))
    op.add_column('clinical_findings', sa.Column('negated', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('clinical_findings', sa.Column('temporality', sa.String(length=50), nullable=True, comment="'current' | 'past' | 'family'"))
    op.add_column('clinical_findings', sa.Column('source_context', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clinical_findings', 'source_context')
    op.drop_column('clinical_findings', 'temporality')
    op.drop_column('clinical_findings', 'negated')
    op.drop_column('clinical_findings', 'certainty')
    op.drop_column('clinical_findings', 'value')
    op.drop_column('clinical_findings', 'concept')
    # ### end Alembic commands ###
