"""Consent Phase 21 updates

Revision ID: a4b13d9ecfff
Revises: 5d35b5547965
Create Date: 2026-09-06 20:54:39.935731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4b13d9ecfff'
down_revision: Union[str, None] = '5d35b5547965'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consent_records', sa.Column('consultation_id', sa.UUID(), nullable=False, comment='Related consultation'))
    op.add_column('consent_records', sa.Column('actor_name', sa.String(length=150), nullable=False, comment='Name of the person giving consent (could be patient, guardian, proxy)'))
    op.add_column('consent_records', sa.Column('actor_relationship', sa.String(length=50), nullable=False, comment="Relationship to patient: 'self', 'parent', 'legal_guardian', etc."))
    op.add_column('consent_records', sa.Column('consent_text_version', sa.String(length=50), server_default='v1.0', nullable=False, comment='Version of the consent script read to the actor'))
    op.add_column('consent_records', sa.Column('purpose', sa.String(length=150), nullable=False, comment="Purpose of consent (e.g. 'Clinical AI Analysis & Recording')"))
    op.add_column('consent_records', sa.Column('status', sa.String(length=30), nullable=False, comment="'granted', 'revoked'"))
    op.add_column('consent_records', sa.Column('recording_permitted', sa.Boolean(), server_default='false', nullable=False, comment='True if audio/ambient recording is explicitly permitted'))
    op.drop_constraint('consent_records_tenant_id_fkey', 'consent_records', type_='foreignkey')
    op.create_foreign_key(None, 'consent_records', 'consultations', ['consultation_id'], ['id'], ondelete='CASCADE')
    op.drop_column('consent_records', 'mechanism')
    op.drop_column('consent_records', 'tenant_id')
    op.drop_column('consent_records', 'consent_type')
    op.drop_column('consent_records', 'scope')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consent_records', sa.Column('scope', sa.TEXT(), autoincrement=False, nullable=False, comment='Description of what was consented to (non-PII)'))
    op.add_column('consent_records', sa.Column('consent_type', sa.VARCHAR(length=40), autoincrement=False, nullable=False, comment="'explicit' | 'implied' | 'revocation'"))
    op.add_column('consent_records', sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False, comment='Tenant scope'))
    op.add_column('consent_records', sa.Column('mechanism', sa.VARCHAR(length=60), autoincrement=False, nullable=False, comment="How consent was obtained: 'verbal' | 'written' | 'electronic'"))
    op.create_foreign_key('fk_consent_records_tenant_id', 'consent_records', 'tenants', ['tenant_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('consent_records', 'recording_permitted')
    op.drop_column('consent_records', 'status')
    op.drop_column('consent_records', 'purpose')
    op.drop_column('consent_records', 'consent_text_version')
    op.drop_column('consent_records', 'actor_relationship')
    op.drop_column('consent_records', 'actor_name')
    op.drop_column('consent_records', 'consultation_id')
    # ### end Alembic commands ###
