"""Add knowledge version to finding

Revision ID: b60679f78807
Revises: 016062e36592
Create Date: 2026-09-06 18:16:34.933749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b60679f78807'
down_revision: Union[str, None] = '016062e36592'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clinical_findings', sa.Column('knowledge_version_id', sa.UUID(), nullable=True, comment='The specific version of the knowledge base that surfaced this finding'))
    op.create_foreign_key(None, 'clinical_findings', 'knowledge_versions', ['knowledge_version_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the anonymous FK on knowledge_version_id using dynamic SQL
    op.execute("""
        DO $$
        DECLARE r RECORD;
        BEGIN
            FOR r IN (
                SELECT tc.constraint_name
                FROM information_schema.table_constraints tc
                JOIN information_schema.key_column_usage kcu
                  ON tc.constraint_name = kcu.constraint_name
                WHERE tc.table_name = 'clinical_findings'
                  AND tc.constraint_type = 'FOREIGN KEY'
                  AND kcu.column_name = 'knowledge_version_id'
            ) LOOP
                EXECUTE 'ALTER TABLE clinical_findings DROP CONSTRAINT IF EXISTS ' || quote_ident(r.constraint_name);
            END LOOP;
        END $$;
    """)
    op.drop_column('clinical_findings', 'knowledge_version_id')
    # ### end Alembic commands ###
