"""Add MLExperiment model

Revision ID: bd6d865d81e7
Revises: e29dbe2ca1cb
Create Date: 2026-09-06 19:57:12.232226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bd6d865d81e7'
down_revision: Union[str, None] = 'e29dbe2ca1cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ml_experiments',
    sa.Column('name', sa.String(length=150), nullable=False, comment="Human-readable name (e.g. 'bert-finetune-v2')"),
    sa.Column('status', sa.String(length=20), server_default='running', nullable=False, comment="'running' | 'completed' | 'failed' | 'aborted'"),
    sa.Column('code_commit', sa.String(length=64), nullable=False, comment='Git commit hash used for this run'),
    sa.Column('dataset_version', sa.String(length=50), nullable=False, comment="Dataset version string (e.g. 'v1.0.0')"),
    sa.Column('dataset_hash', sa.String(length=128), nullable=False, comment='SHA-256 hash of the dataset used'),
    sa.Column('preprocessing_version', sa.String(length=50), server_default='1.0', nullable=False, comment='Version of the preprocessing/tokenization pipeline'),
    sa.Column('model_name', sa.String(length=100), nullable=False, comment="Base model (e.g. 'clinical-bert-base')"),
    sa.Column('configuration', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False, comment='Hyperparameters (learning rate, batch size, etc.)'),
    sa.Column('random_seed', sa.Float(), nullable=False, comment='Random seed for framework (PyTorch/TF/NumPy)'),
    sa.Column('hardware', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False, comment="Hardware topology (e.g. '8x A100 80GB')"),
    sa.Column('execution_duration_sec', sa.Float(), nullable=True, comment='Total runtime in seconds'),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False, comment='Recorded metrics (loss, accuracy, F1, etc.)'),
    sa.Column('artifact_location', sa.String(length=500), nullable=True, comment='URI to the trained weights/outputs in object storage'),
    sa.Column('id', sa.Uuid(), nullable=False, comment='Primary key (UUID v4, generated at INSERT)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Row insertion timestamp (UTC, server-set)'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Last modification timestamp (UTC, server-set)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ml_experiments_commit', 'ml_experiments', ['code_commit'], unique=False)
    op.create_index('ix_ml_experiments_status', 'ml_experiments', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ml_experiments_status', table_name='ml_experiments')
    op.drop_index('ix_ml_experiments_commit', table_name='ml_experiments')
    op.drop_table('ml_experiments')
    # ### end Alembic commands ###
