"""phase9_core_clinical_data_model

Revision ID: c52ef03ed888
Revises: 0003
Create Date: 2026-09-06 12:12:17.928331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c52ef03ed888'
down_revision: Union[str, None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('code', sa.String(length=120), nullable=False, comment='Machine-readable capability code, globally unique'),
    sa.Column('description', sa.Text(), nullable=True, comment='Human-readable description of this capability'),
    sa.Column('resource', sa.String(length=60), nullable=False, comment="Resource domain (e.g. 'consultation', 'patient_session')"),
    sa.Column('action', sa.String(length=40), nullable=False, comment="Action (e.g. 'create', 'read', 'update', 'delete')"),
    sa.Column('id', sa.Uuid(), nullable=False, comment='Primary key (UUID v4, generated at INSERT)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Row insertion timestamp (UTC, server-set)'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Last modification timestamp (UTC, server-set)'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('ix_permissions_code', 'permissions', ['code'], unique=True)
    op.create_table('sources',
    sa.Column('code', sa.String(length=80), nullable=False, comment="Internal unique code (e.g. 'pubmed', 'rxnorm', 'who_guidelines')"),
    sa.Column('organisation', sa.String(length=200), nullable=False, comment="Publishing organisation (e.g. 'NIH / NLM', 'WHO')"),
    sa.Column('name', sa.String(length=200), nullable=False, comment="Source name (e.g. 'PubMed Central', 'RxNorm')"),
    sa.Column('base_url', sa.String(length=500), nullable=True, comment='Base URL or API endpoint'),
    sa.Column('access_mechanism', sa.String(length=60), server_default='api', nullable=False, comment="'api' | 'bulk_download' | 'manual' | 'licensed_feed'"),
    sa.Column('data_type', sa.String(length=60), nullable=False, comment="'literature' | 'drug_database' | 'clinical_guidelines' | 'coding_system'"),
    sa.Column('license_info', sa.Text(), nullable=True, comment='License / access terms (must be verified before ingestion)'),
    sa.Column('is_production_suitable', sa.Boolean(), server_default='false', nullable=False, comment='True only after licensing and quality review by admin'),
    sa.Column('last_verified_at', sa.String(length=30), nullable=True, comment='ISO-8601 date when access/licensing was last confirmed'),
    sa.Column('status', sa.String(length=20), server_default='registered', nullable=False, comment="'registered' | 'active' | 'suspended' | 'retired'"),
    sa.Column('id', sa.Uuid(), nullable=False, comment='Primary key (UUID v4, generated at INSERT)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Row insertion timestamp (UTC, server-set)'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Last modification timestamp (UTC, server-set)'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('ix_sources_code', 'sources', ['code'], unique=True)
    op.create_table('tenants',
    sa.Column('name', sa.String(length=200), nullable=False, comment='Display name of the organisation'),
    sa.Column('slug', sa.String(length=80), nullable=False, comment='URL-safe unique identifier (lowercase, hyphens only)'),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False, comment="Lifecycle: 'active' | 'suspended' | 'archived'"),
    sa.Column('plan', sa.String(length=40), server_default='trial', nullable=False, comment="Subscription plan: 'trial' | 'standard' | 'enterprise'"),
    sa.Column('contact_email', sa.String(length=320), nullable=True, comment='Primary contact email for the tenant'),
    sa.Column('is_verified', sa.Boolean(), server_default='false', nullable=False, comment='True once the tenant organisation has been KYB-verified'),
    sa.Column('settings', sa.Text(), nullable=True, comment='JSON blob for tenant-specific feature flags and preferences'),
    sa.Column('id', sa.Uuid(), nullable=False, comment='Primary key (UUID v4, generated at INSERT)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Row insertion timestamp (UTC, server-set)'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Last modification timestamp (UTC, server-set)'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('ix_tenants_slug', 'tenants', ['slug'], unique=True)
    op.create_table('articles',
    sa.Column('source_id', sa.UUID(), nullable=False, comment='Origin source'),
    sa.Column('title', sa.Text(), nullable=False, comment='Article or guideline title'),
    sa.Column('authors', sa.Text(), nullable=True, comment='Author list (plain text, not structured)'),
    sa.Column('doi', sa.String(length=200), nullable=True, comment='Digital Object Identifier'),
    sa.Column('pmid', sa.String(length=20), nullable=True, comment='PubMed ID'),
    sa.Column('published_date', sa.String(length=10), nullable=True, comment='ISO-8601 publication date (YYYY-MM-DD or YYYY-MM)'),
    sa.Column('journal', sa.String(length=300), nullable=True, comment='Journal or guideline body name'),
    sa.Column('abstract', sa.Text(), nullable=True, comment='Abstract or summary (sourced verbatim — do not paraphrase or fabricate)'),
    sa.Column('url', sa.String(length=500), nullable=True, comment='URL for full-text access'),
    sa.Column('retrieval_status', sa.String(length=20), server_default='indexed', nullable=False, comment="'indexed' | 'full_text' | 'unavailable'"),
    sa.Column('id', sa.Uuid(), nullable=False, comment='Primary key (UUID v4, generated at INSERT)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Row insertion timestamp (UTC, server-set)'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Last modification timestamp (UTC, server-set)'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_articles_doi', 'articles', ['doi'], unique=False)
    op.create_index('ix_articles_pmid', 'articles', ['pmid'], unique=False)
    op.create_index('ix_articles_source', 'articles', ['source_id'], unique=False)
    op.create_index(op.f('ix_articles_source_id'), 'articles', ['source_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='When this audit event was recorded'),
    sa.Column('tenant_id', sa.UUID(), nullable=True, comment='Tenant context (null for system-level events)'),
    sa.Column('actor_id', sa.UUID(), nullable=True, comment='User who performed the action (null for automated/system actions)'),
    sa.Column('action', sa.String(length=120), nullable=False, comment="Past-tense verb (e.g. 'consultation.submitted', 'finding.confirmed')"),
    sa.Column('entity_type', sa.String(length=60), nullable=False, comment="Type of entity affected (e.g. 'consultation', 'clinical_note')"),
    sa.Column('entity_id', sa.UUID(), nullable=True, comment='UUID of the affected entity (null for non-entity events)'),
    sa.Column('ip_address', sa.String(length=45), nullable=True, comment='IPv4 or IPv6 address of the requestor'),
    sa.Column('user_agent', sa.String(length=300), nullable=True, comment='HTTP User-Agent header of the requestor'),
    sa.Column('request_id', sa.String(length=40), nullable=True, comment='X-Request-ID for correlation with access logs'),
    sa.Column('diff', sa.Text(), nullable=True, comment='JSON diff of changed fields (old/new) — no PII'),
    sa.Column('severity', sa.String(length=20), server_default='info', nullable=False, comment="'info' | 'warning' | 'critical'"),
    sa.Column('id', sa.Uuid(), nullable=False, comment='Primary key (UUID v4, generated at INSERT)'),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_actor', 'audit_logs', ['actor_id'], unique=False)
    op.create_index('ix_audit_logs_created_at', 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_logs_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index('ix_audit_logs_tenant', 'audit_logs', ['tenant_id'], unique=False)
    op.create_table('doctors',
    sa.Column('user_id', sa.UUID(), nullable=False, comment='One-to-one with users table'),
    sa.Column('tenant_id', sa.UUID(), nullable=True, comment='Employing organisation (nullable until assigned)'),
    sa.Column('specialty', sa.String(length=120), nullable=True, comment="Medical specialty (e.g. 'Cardiology', 'General Practice')"),
    sa.Column('credential_reference', sa.String(length=200), nullable=True, comment='Medical registration / license number (opaque reference)'),
    sa.Column('credential_body', sa.String(length=120), nullable=True, comment="Issuing body (e.g. 'GMC', 'NMC', 'MCI')"),
    sa.Column('bio', sa.Text(), nullable=True, comment='Professional biography (optional)'),
    sa.Column('verification_status', sa.String(length=20), server_default='pending', nullable=False, comment="Verification: 'pending' | 'verified' | 'rejected'"),
    sa.Column('verified_by_id', sa.UUID(), nullable=True, comment='Admin user who approved/rejected verification'),
    sa.Column('rejection_reason', sa.Text(), nullable=True, comment="Admin-provided reason if verification_status='rejected'"),
    sa.Column('id', sa.Uuid(), nullable=False, comment='Primary key (UUID v4, generated at INSERT)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Row insertion timestamp (UTC, server-set)'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Last modification timestamp (UTC, server-set)'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('ix_doctors_tenant_id', 'doctors', ['tenant_id'], unique=False)
    op.create_index('ix_doctors_user_id', 'doctors', ['user_id'], unique=True)
    op.create_table('file_objects',
    sa.Column('owner_id', sa.UUID(), nullable=False, comment='User who uploaded this file'),
    sa.Column('tenant_id', sa.UUID(), nullable=True, comment='Tenant scope'),
    sa.Column('object_key', sa.String(length=400), nullable=False, comment='Server-generated object storage key (not user-supplied path)'),
    sa.Column('original_filename', sa.String(length=260), nullable=False, comment='Original filename as supplied by the client (display only)'),
    sa.Column('mime_type', sa.String(length=120), nullable=False, comment='Server-verified MIME type (not trusted from client)'),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False, comment='File size in bytes'),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=True, comment='SHA-256 hex digest of file contents'),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False, comment="'pending' | 'ready' | 'quarantined' | 'deleted'"),
    sa.Column('scan_status', sa.String(length=20), server_default='pending', nullable=False, comment="Virus scan status: 'pending' | 'clean' | 'infected' | 'failed'"),
    sa.Column('retention_until', sa.String(length=30), nullable=True, comment='ISO-8601 retention date; null = indefinite'),
    sa.Column('linked_entity_type', sa.String(length=60), nullable=True, comment='Entity type this file is attached to (polymorphic)'),
    sa.Column('linked_entity_id', sa.UUID(), nullable=True, comment='UUID of the entity this file is attached to'),
    sa.Column('id', sa.Uuid(), nullable=False, comment='Primary key (UUID v4, generated at INSERT)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Row insertion timestamp (UTC, server-set)'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Last modification timestamp (UTC, server-set)'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('object_key')
    )
    op.create_index('ix_file_objects_key', 'file_objects', ['object_key'], unique=True)
    op.create_index('ix_file_objects_owner', 'file_objects', ['owner_id'], unique=False)
    op.create_index('ix_file_objects_tenant', 'file_objects', ['tenant_id'], unique=False)
    op.create_table('knowledge_versions',
    sa.Column('tag', sa.String(length=60), nullable=False, comment="Semantic version tag (e.g. '2026.09.1') — globally unique"),
    sa.Column('description', sa.Text(), nullable=True, comment='Summary of changes in this knowledge version'),
    sa.Column('status', sa.String(length=20), server_default='draft', nullable=False, comment="'draft' | 'published' | 'archived'"),
    sa.Column('published_by_id', sa.UUID(), nullable=True, comment='Admin who published this version'),
    sa.Column('id', sa.Uuid(), nullable=False, comment='Primary key (UUID v4, generated at INSERT)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Row insertion timestamp (UTC, server-set)'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Last modification timestamp (UTC, server-set)'),
    sa.ForeignKeyConstraint(['published_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tag')
    )
    op.create_index('ix_knowledge_versions_tag', 'knowledge_versions', ['tag'], unique=True)
    op.create_table('roles',
    sa.Column('tenant_id', sa.UUID(), nullable=False, comment='Owning tenant (roles are tenant-scoped)'),
    sa.Column('name', sa.String(length=80), nullable=False, comment="Role name (unique per tenant, e.g. 'senior_doctor')"),
    sa.Column('description', sa.Text(), nullable=True, comment='Human-readable description of this role'),
    sa.Column('is_system', sa.Boolean(), server_default='false', nullable=False, comment='True for built-in roles that cannot be deleted'),
    sa.Column('id', sa.Uuid(), nullable=False, comment='Primary key (UUID v4, generated at INSERT)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Row insertion timestamp (UTC, server-set)'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Last modification timestamp (UTC, server-set)'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_roles_tenant_name')
    )
    op.create_index(op.f('ix_roles_tenant_id'), 'roles', ['tenant_id'], unique=False)
    op.create_table('clinical_findings',
    sa.Column('consultation_id', sa.UUID(), nullable=False, comment='Parent consultation'),
    sa.Column('finding_text', sa.Text(), nullable=False, comment='Non-PII description of the finding'),
    sa.Column('finding_type', sa.String(length=40), nullable=False, comment="'symptom' | 'sign' | 'measurement' | 'diagnosis' | 'risk_factor'"),
    sa.Column('is_ai_suggested', sa.Boolean(), server_default='false', nullable=False, comment='True if this finding was surfaced by AI (not yet clinician-confirmed)'),
    sa.Column('is_clinician_confirmed', sa.Boolean(), server_default='false', nullable=False, comment='True only when a clinician has explicitly confirmed this finding'),
    sa.Column('confirmed_by_id', sa.UUID(), nullable=True, comment='Clinician who confirmed this finding (null if unconfirmed)'),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False, comment="'pending' | 'confirmed' | 'rejected' | 'superseded'"),
    sa.Column('confidence_score', sa.Float(), nullable=True, comment='AI confidence score [0.0–1.0] (null for clinician-entered findings)'),
    sa.Column('id', sa.Uuid(), nullable=False, comment='Primary key (UUID v4, generated at INSERT)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Row insertion timestamp (UTC, server-set)'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Last modification timestamp (UTC, server-set)'),
    sa.ForeignKeyConstraint(['confirmed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_clinical_findings_consultation', 'clinical_findings', ['consultation_id'], unique=False)
    op.create_index(op.f('ix_clinical_findings_consultation_id'), 'clinical_findings', ['consultation_id'], unique=False)
    op.create_index('ix_clinical_findings_status', 'clinical_findings', ['status'], unique=False)
    op.create_table('clinical_notes',
    sa.Column('consultation_id', sa.UUID(), nullable=False, comment='Parent consultation'),
    sa.Column('author_id', sa.UUID(), nullable=False, comment='Clinician who authored this note'),
    sa.Column('note_type', sa.String(length=40), server_default='progress', nullable=False, comment="'history' | 'examination' | 'progress' | 'discharge' | 'referral'"),
    sa.Column('body', sa.Text(), nullable=False, comment='Note text (non-PII narrative; clinician-confirmed content only)'),
    sa.Column('status', sa.String(length=20), server_default='draft', nullable=False, comment="'draft' | 'final' | 'amended' | 'voided'"),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False, comment='Monotonically increasing version number'),
    sa.Column('is_ai_generated', sa.Boolean(), server_default='false', nullable=False, comment='True if this note was AI-drafted (requires clinician review)'),
    sa.Column('id', sa.Uuid(), nullable=False, comment='Primary key (UUID v4, generated at INSERT)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Row insertion timestamp (UTC, server-set)'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Last modification timestamp (UTC, server-set)'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_clinical_notes_consultation', 'clinical_notes', ['consultation_id'], unique=False)
    op.create_index(op.f('ix_clinical_notes_consultation_id'), 'clinical_notes', ['consultation_id'], unique=False)
    op.create_table('diseases',
    sa.Column('code', sa.String(length=80), nullable=False, comment='Canonical code (internal slug or ICD-10)'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='Human-readable disease name'),
    sa.Column('description', sa.Text(), nullable=True, comment='Clinical description — sourced from verified reference only'),
    sa.Column('icd10_code', sa.String(length=20), nullable=True, comment='ICD-10 code'),
    sa.Column('icd11_code', sa.String(length=20), nullable=True, comment='ICD-11 code'),
    sa.Column('snomed_id', sa.String(length=40), nullable=True, comment='SNOMED CT concept ID'),
    sa.Column('category', sa.String(length=80), nullable=True, comment="Clinical category (e.g. 'infectious', 'cardiovascular')"),
    sa.Column('status', sa.String(length=20), server_default='draft', nullable=False, comment="'draft' | 'verified' | 'deprecated'"),
    sa.Column('is_ai_generated', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('knowledge_version_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False, comment='Primary key (UUID v4, generated at INSERT)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Row insertion timestamp (UTC, server-set)'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Last modification timestamp (UTC, server-set)'),
    sa.ForeignKeyConstraint(['knowledge_version_id'], ['knowledge_versions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('ix_diseases_code', 'diseases', ['code'], unique=True)
    op.create_index('ix_diseases_status', 'diseases', ['status'], unique=False)
    op.create_table('evidence',
    sa.Column('article_id', sa.UUID(), nullable=False, comment='Supporting article or guideline'),
    sa.Column('entity_type', sa.String(length=40), nullable=False, comment="'disease' | 'symptom' | 'investigation' | 'medicine'"),
    sa.Column('entity_id', sa.UUID(), nullable=False, comment='UUID of the referenced entity (no FK — polymorphic)'),
    sa.Column('claim', sa.Text(), nullable=False, comment='The specific clinical claim this evidence supports'),
    sa.Column('evidence_grade', sa.String(length=5), nullable=True, comment='EBM grade: Ia | Ib | IIa | IIb | III | IV'),
    sa.Column('recommendation_grade', sa.String(length=5), nullable=True, comment='Recommendation grade: A | B | C | D | GPP'),
    sa.Column('is_ai_extracted', sa.Boolean(), server_default='false', nullable=False, comment='True if evidence was extracted by AI (requires expert review)'),
    sa.Column('reviewed_by_id', sa.UUID(), nullable=True, comment='Expert who reviewed AI-extracted evidence'),
    sa.Column('id', sa.Uuid(), nullable=False, comment='Primary key (UUID v4, generated at INSERT)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Row insertion timestamp (UTC, server-set)'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Last modification timestamp (UTC, server-set)'),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_evidence_article', 'evidence', ['article_id'], unique=False)
    op.create_index(op.f('ix_evidence_article_id'), 'evidence', ['article_id'], unique=False)
    op.create_index('ix_evidence_entity', 'evidence', ['entity_type', 'entity_id'], unique=False)
    op.create_table('feedback',
    sa.Column('consultation_id', sa.UUID(), nullable=False, comment='Consultation this feedback relates to'),
    sa.Column('clinician_id', sa.UUID(), nullable=False, comment='Clinician providing feedback'),
    sa.Column('target_type', sa.String(length=40), nullable=False, comment="'finding' | 'investigation' | 'medicine' | 'overall'"),
    sa.Column('target_id', sa.UUID(), nullable=True, comment='UUID of the specific AI suggestion being rated (null for overall)'),
    sa.Column('rating', sa.Integer(), nullable=True, comment='1–5 Likert rating (null if free-text only)'),
    sa.Column('is_correct', sa.Boolean(), nullable=True, comment='Binary correct/incorrect assessment (null if not applicable)'),
    sa.Column('comment', sa.Text(), nullable=True, comment='Free-text feedback (non-PII)'),
    sa.Column('id', sa.Uuid(), nullable=False, comment='Primary key (UUID v4, generated at INSERT)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Row insertion timestamp (UTC, server-set)'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Last modification timestamp (UTC, server-set)'),
    sa.ForeignKeyConstraint(['clinician_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_feedback_clinician', 'feedback', ['clinician_id'], unique=False)
    op.create_index('ix_feedback_consultation', 'feedback', ['consultation_id'], unique=False)
    op.create_index(op.f('ix_feedback_consultation_id'), 'feedback', ['consultation_id'], unique=False)
    op.create_table('investigations',
    sa.Column('code', sa.String(length=80), nullable=False, comment='Canonical code (LOINC, SNOMED, or internal slug)'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='Human-readable name'),
    sa.Column('description', sa.Text(), nullable=True, comment='Clinical description — sourced from verified reference only'),
    sa.Column('loinc_code', sa.String(length=20), nullable=True, comment='LOINC code if applicable'),
    sa.Column('investigation_type', sa.String(length=40), server_default='laboratory', nullable=False, comment="'laboratory' | 'imaging' | 'procedure' | 'questionnaire'"),
    sa.Column('status', sa.String(length=20), server_default='draft', nullable=False, comment="'draft' | 'verified' | 'deprecated'"),
    sa.Column('is_ai_generated', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('knowledge_version_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False, comment='Primary key (UUID v4, generated at INSERT)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Row insertion timestamp (UTC, server-set)'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Last modification timestamp (UTC, server-set)'),
    sa.ForeignKeyConstraint(['knowledge_version_id'], ['knowledge_versions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('ix_investigations_code', 'investigations', ['code'], unique=True)
    op.create_table('medicines',
    sa.Column('code', sa.String(length=80), nullable=False, comment='Internal slug or RxNorm CUI'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='Generic (INN) name'),
    sa.Column('brand_names', sa.Text(), nullable=True, comment='Comma-separated brand names (informational only)'),
    sa.Column('atc_code', sa.String(length=20), nullable=True, comment='WHO ATC classification code'),
    sa.Column('rxnorm_cui', sa.String(length=20), nullable=True, comment='RxNorm Concept Unique Identifier'),
    sa.Column('drug_class', sa.String(length=120), nullable=True, comment='Pharmacological class'),
    sa.Column('mechanism_of_action', sa.Text(), nullable=True, comment='Brief mechanism of action (reference only; clinician review required)'),
    sa.Column('status', sa.String(length=20), server_default='draft', nullable=False, comment="'draft' | 'verified' | 'deprecated'"),
    sa.Column('is_ai_generated', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('knowledge_version_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False, comment='Primary key (UUID v4, generated at INSERT)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Row insertion timestamp (UTC, server-set)'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Last modification timestamp (UTC, server-set)'),
    sa.ForeignKeyConstraint(['knowledge_version_id'], ['knowledge_versions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('ix_medicines_code', 'medicines', ['code'], unique=True)
    op.create_table('patient_sessions',
    sa.Column('tenant_id', sa.UUID(), nullable=False, comment='Owning tenant'),
    sa.Column('doctor_id', sa.UUID(), nullable=False, comment='Attending doctor (FK to doctors, not users)'),
    sa.Column('patient_ref', sa.String(length=200), nullable=False, comment='Opaque external reference from EMR/HIS. NOT a real name, NHS number, or any direct identifier.'),
    sa.Column('encounter_type', sa.String(length=60), server_default='outpatient', nullable=False, comment="'inpatient' | 'outpatient' | 'emergency' | 'telemedicine'"),
    sa.Column('status', sa.String(length=20), server_default='open', nullable=False, comment="Lifecycle: 'open' | 'closed' | 'archived'"),
    sa.Column('clinical_notes_summary', sa.Text(), nullable=True, comment='Non-identifying encounter summary (no PII)'),
    sa.Column('id', sa.Uuid(), nullable=False, comment='Primary key (UUID v4, generated at INSERT)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Row insertion timestamp (UTC, server-set)'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Last modification timestamp (UTC, server-set)'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_sessions_doctor_id'), 'patient_sessions', ['doctor_id'], unique=False)
    op.create_index('ix_patient_sessions_status', 'patient_sessions', ['status'], unique=False)
    op.create_index('ix_patient_sessions_tenant_doctor', 'patient_sessions', ['tenant_id', 'doctor_id'], unique=False)
    op.create_index(op.f('ix_patient_sessions_tenant_id'), 'patient_sessions', ['tenant_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.UUID(), nullable=False, comment='FK to role'),
    sa.Column('permission_id', sa.UUID(), nullable=False, comment='FK to permission'),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id'),
    sa.UniqueConstraint('role_id', 'permission_id', name='uq_role_permissions')
    )
    op.create_table('symptoms',
    sa.Column('code', sa.String(length=80), nullable=False, comment='Canonical code (e.g. SNOMED CT concept ID or internal slug)'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='Human-readable symptom name'),
    sa.Column('description', sa.Text(), nullable=True, comment='Clinical description — sourced from verified reference only'),
    sa.Column('icd10_code', sa.String(length=20), nullable=True, comment='Optional ICD-10 code mapping'),
    sa.Column('snomed_id', sa.String(length=40), nullable=True, comment='Optional SNOMED CT concept ID'),
    sa.Column('status', sa.String(length=20), server_default='draft', nullable=False, comment="'draft' | 'verified' | 'deprecated'"),
    sa.Column('is_ai_generated', sa.Boolean(), server_default='false', nullable=False, comment='True if content was AI-generated (requires clinician review)'),
    sa.Column('knowledge_version_id', sa.UUID(), nullable=True, comment='FK to the knowledge version when this record was created/updated'),
    sa.Column('id', sa.Uuid(), nullable=False, comment='Primary key (UUID v4, generated at INSERT)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Row insertion timestamp (UTC, server-set)'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Last modification timestamp (UTC, server-set)'),
    sa.ForeignKeyConstraint(['knowledge_version_id'], ['knowledge_versions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('ix_symptoms_code', 'symptoms', ['code'], unique=True)
    op.create_index('ix_symptoms_status', 'symptoms', ['status'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.UUID(), nullable=False, comment='FK to user'),
    sa.Column('role_id', sa.UUID(), nullable=False, comment='FK to role'),
    sa.Column('tenant_id', sa.UUID(), nullable=False, comment='Tenant scope for this assignment'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id'),
    sa.UniqueConstraint('user_id', 'role_id', 'tenant_id', name='uq_user_roles')
    )
    op.create_table('consent_records',
    sa.Column('patient_session_id', sa.UUID(), nullable=False, comment='Related patient session'),
    sa.Column('tenant_id', sa.UUID(), nullable=False, comment='Tenant scope'),
    sa.Column('consent_type', sa.String(length=40), nullable=False, comment="'explicit' | 'implied' | 'revocation'"),
    sa.Column('mechanism', sa.String(length=60), nullable=False, comment="How consent was obtained: 'verbal' | 'written' | 'electronic'"),
    sa.Column('scope', sa.Text(), nullable=False, comment='Description of what was consented to (non-PII)'),
    sa.Column('recorded_by_id', sa.UUID(), nullable=False, comment='Clinician who recorded this consent'),
    sa.Column('id', sa.Uuid(), nullable=False, comment='Primary key (UUID v4, generated at INSERT)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Row insertion timestamp (UTC, server-set)'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Last modification timestamp (UTC, server-set)'),
    sa.ForeignKeyConstraint(['patient_session_id'], ['patient_sessions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consent_records_patient_session_id'), 'consent_records', ['patient_session_id'], unique=False)
    op.create_index('ix_consent_records_session', 'consent_records', ['patient_session_id'], unique=False)
    op.create_table('disease_investigations',
    sa.Column('disease_id', sa.UUID(), nullable=False),
    sa.Column('investigation_id', sa.UUID(), nullable=False),
    sa.Column('indication', sa.String(length=80), nullable=True, comment="'diagnostic' | 'monitoring' | 'screening'"),
    sa.Column('priority', sa.String(length=20), nullable=True, comment="'first_line' | 'second_line' | 'adjunct'"),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['disease_id'], ['diseases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('disease_id', 'investigation_id'),
    sa.UniqueConstraint('disease_id', 'investigation_id', name='uq_disease_investigation')
    )
    op.create_table('disease_medicines',
    sa.Column('disease_id', sa.UUID(), nullable=False),
    sa.Column('medicine_id', sa.UUID(), nullable=False),
    sa.Column('treatment_role', sa.String(length=40), nullable=True, comment="'first_line' | 'second_line' | 'adjunct' | 'prophylaxis'"),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['disease_id'], ['diseases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('disease_id', 'medicine_id'),
    sa.UniqueConstraint('disease_id', 'medicine_id', name='uq_disease_medicine')
    )
    op.create_table('disease_symptoms',
    sa.Column('disease_id', sa.UUID(), nullable=False),
    sa.Column('symptom_id', sa.UUID(), nullable=False),
    sa.Column('frequency', sa.String(length=40), nullable=True, comment="'very_common' | 'common' | 'uncommon' | 'rare' | 'very_rare'"),
    sa.Column('specificity', sa.Float(), nullable=True, comment='Diagnostic specificity [0.0–1.0] from literature (reference only)'),
    sa.Column('source_id', sa.UUID(), nullable=True, comment='Source from which this association was derived'),
    sa.ForeignKeyConstraint(['disease_id'], ['diseases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['symptom_id'], ['symptoms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('disease_id', 'symptom_id'),
    sa.UniqueConstraint('disease_id', 'symptom_id', name='uq_disease_symptom')
    )
    op.alter_column('consultations', 'placeholder_response',
               existing_type=sa.TEXT(),
               comment='Non-clinical placeholder response (development only). Always prefixed with the mandatory safety label.',
               existing_comment='Non-clinical placeholder response (development only).',
               existing_nullable=True)
    op.create_index(op.f('ix_consultations_user_id'), 'consultations', ['user_id'], unique=False)
    op.drop_index(op.f('users_email_lower_idx'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('users_email_lower_idx'), 'users', [sa.literal_column('lower(email::text)')], unique=True)
    op.drop_index(op.f('ix_consultations_user_id'), table_name='consultations')
    op.alter_column('consultations', 'placeholder_response',
               existing_type=sa.TEXT(),
               comment='Non-clinical placeholder response (development only).',
               existing_comment='Non-clinical placeholder response (development only). Always prefixed with the mandatory safety label.',
               existing_nullable=True)
    op.drop_table('disease_symptoms')
    op.drop_table('disease_medicines')
    op.drop_table('disease_investigations')
    op.drop_index('ix_consent_records_session', table_name='consent_records')
    op.drop_index(op.f('ix_consent_records_patient_session_id'), table_name='consent_records')
    op.drop_table('consent_records')
    op.drop_table('user_roles')
    op.drop_index('ix_symptoms_status', table_name='symptoms')
    op.drop_index('ix_symptoms_code', table_name='symptoms')
    op.drop_table('symptoms')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_patient_sessions_tenant_id'), table_name='patient_sessions')
    op.drop_index('ix_patient_sessions_tenant_doctor', table_name='patient_sessions')
    op.drop_index('ix_patient_sessions_status', table_name='patient_sessions')
    op.drop_index(op.f('ix_patient_sessions_doctor_id'), table_name='patient_sessions')
    op.drop_table('patient_sessions')
    op.drop_index('ix_medicines_code', table_name='medicines')
    op.drop_table('medicines')
    op.drop_index('ix_investigations_code', table_name='investigations')
    op.drop_table('investigations')
    op.drop_index(op.f('ix_feedback_consultation_id'), table_name='feedback')
    op.drop_index('ix_feedback_consultation', table_name='feedback')
    op.drop_index('ix_feedback_clinician', table_name='feedback')
    op.drop_table('feedback')
    op.drop_index('ix_evidence_entity', table_name='evidence')
    op.drop_index(op.f('ix_evidence_article_id'), table_name='evidence')
    op.drop_index('ix_evidence_article', table_name='evidence')
    op.drop_table('evidence')
    op.drop_index('ix_diseases_status', table_name='diseases')
    op.drop_index('ix_diseases_code', table_name='diseases')
    op.drop_table('diseases')
    op.drop_index(op.f('ix_clinical_notes_consultation_id'), table_name='clinical_notes')
    op.drop_index('ix_clinical_notes_consultation', table_name='clinical_notes')
    op.drop_table('clinical_notes')
    op.drop_index('ix_clinical_findings_status', table_name='clinical_findings')
    op.drop_index(op.f('ix_clinical_findings_consultation_id'), table_name='clinical_findings')
    op.drop_index('ix_clinical_findings_consultation', table_name='clinical_findings')
    op.drop_table('clinical_findings')
    op.drop_index(op.f('ix_roles_tenant_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index('ix_knowledge_versions_tag', table_name='knowledge_versions')
    op.drop_table('knowledge_versions')
    op.drop_index('ix_file_objects_tenant', table_name='file_objects')
    op.drop_index('ix_file_objects_owner', table_name='file_objects')
    op.drop_index('ix_file_objects_key', table_name='file_objects')
    op.drop_table('file_objects')
    op.drop_index('ix_doctors_user_id', table_name='doctors')
    op.drop_index('ix_doctors_tenant_id', table_name='doctors')
    op.drop_table('doctors')
    op.drop_index('ix_audit_logs_tenant', table_name='audit_logs')
    op.drop_index('ix_audit_logs_entity', table_name='audit_logs')
    op.drop_index('ix_audit_logs_created_at', table_name='audit_logs')
    op.drop_index('ix_audit_logs_actor', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_articles_source_id'), table_name='articles')
    op.drop_index('ix_articles_source', table_name='articles')
    op.drop_index('ix_articles_pmid', table_name='articles')
    op.drop_index('ix_articles_doi', table_name='articles')
    op.drop_table('articles')
    op.drop_index('ix_tenants_slug', table_name='tenants')
    op.drop_table('tenants')
    op.drop_index('ix_sources_code', table_name='sources')
    op.drop_table('sources')
    op.drop_index('ix_permissions_code', table_name='permissions')
    op.drop_table('permissions')
    # ### end Alembic commands ###
