"""Phase 29 Concept Normalization fields

Revision ID: cf99026fe3fe
Revises: 6a8fe758c63e
Create Date: 2026-09-07 00:03:08.087357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf99026fe3fe'
down_revision: Union[str, None] = '6a8fe758c63e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clinical_findings', sa.Column('canonical_concept', sa.String(length=255), nullable=True, comment='Normalized verified term'))
    op.add_column('clinical_findings', sa.Column('mapping_source', sa.String(length=100), nullable=True, comment="e.g. 'internal_dict', 'snomed'"))
    op.add_column('clinical_findings', sa.Column('mapping_confidence', sa.Float(), nullable=True, comment='Confidence of the normalization mapping'))
    op.alter_column('clinical_findings', 'value',
               existing_type=sa.TEXT(),
               comment='Raw extracted value',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clinical_findings', 'value',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Raw extracted value',
               existing_nullable=True)
    op.drop_column('clinical_findings', 'mapping_confidence')
    op.drop_column('clinical_findings', 'mapping_source')
    op.drop_column('clinical_findings', 'canonical_concept')
    # ### end Alembic commands ###
