"""Add immutable_hash to consultations

Revision ID: eaaf403c7a08
Revises: 163d47bee688
Create Date: 2026-09-12 14:09:58.601357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = 'eaaf403c7a08'
down_revision: Union[str, None] = '163d47bee688'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
    DO $$
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'modellifecyclestate') THEN
            CREATE TYPE modellifecyclestate AS ENUM ('EXPERIMENTAL', 'EVALUATED', 'CANDIDATE', 'SAFETY_REVIEW', 'APPROVED', 'STAGING', 'PRODUCTION', 'RETIRED');
        END IF;
    END$$;
    """)
    from sqlalchemy.dialects import postgresql
    op.create_table('ml_registered_models',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('base_model', sa.String(length=255), nullable=False),
    sa.Column('adapter_name', sa.String(length=255), nullable=True),
    sa.Column('dataset_version', sa.String(length=50), nullable=True),
    sa.Column('evaluation_version', sa.String(length=50), nullable=True),
    sa.Column('lifecycle_state', postgresql.ENUM('EXPERIMENTAL', 'EVALUATED', 'CANDIDATE', 'SAFETY_REVIEW', 'APPROVED', 'STAGING', 'PRODUCTION', 'RETIRED', name='modellifecyclestate', create_type=False), nullable=False),
    sa.Column('artifact_location', sa.String(length=1024), nullable=True),
    sa.Column('safety_results', sa.JSON(), nullable=True),
    sa.Column('deployment_date', sa.DateTime(), nullable=True),
    sa.Column('rollback_version', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('consultations', sa.Column('immutable_hash', sa.String(), nullable=True, comment='Phase 73: Clinical Immutability Record'))
    op.create_index(op.f('ix_consultations_immutable_hash'), 'consultations', ['immutable_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_consultations_immutable_hash'), table_name='consultations')
    op.drop_column('consultations', 'immutable_hash')
    op.drop_table('ml_registered_models')
    op.execute("DROP TYPE IF EXISTS modellifecyclestate CASCADE")
    # ### end Alembic commands ###
