"""add_clinician_feedback

Revision ID: ed896898f8a8
Revises: 12755713377a
Create Date: 2026-09-11 23:28:26.671299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ed896898f8a8'
down_revision: Union[str, None] = '12755713377a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient_profiles',
    sa.Column('tenant_id', sa.UUID(), nullable=False, comment='Owning tenant'),
    sa.Column('patient_ref', sa.String(length=200), nullable=False, comment='Opaque external reference from EMR/HIS. NOT a real name, NHS number, or any direct identifier.'),
    sa.Column('age_group', sa.String(length=20), nullable=True, comment="Pseudo-demographic: e.g., '18-25', '60-70'"),
    sa.Column('biological_sex', sa.String(length=20), nullable=True, comment="Biological sex: 'male', 'female', 'other', 'unknown'"),
    sa.Column('baseline_conditions', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False, comment='JSON containing known past medical history / chronic conditions'),
    sa.Column('id', sa.Uuid(), nullable=False, comment='Primary key (UUID v4, generated at INSERT)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Row insertion timestamp (UTC, server-set)'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Last modification timestamp (UTC, server-set)'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'patient_ref', name='uq_tenant_patient_ref')
    )
    op.create_index('ix_patient_profiles_tenant', 'patient_profiles', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_patient_profiles_tenant_id'), 'patient_profiles', ['tenant_id'], unique=False)
    op.create_table('clinician_feedback',
    sa.Column('suggestion_id', sa.String(length=100), nullable=False, comment='Unique identifier for the suggestion being evaluated'),
    sa.Column('suggestion_type', sa.String(length=50), nullable=False, comment="e.g., 'clinical_note', 'diagnosis', 'investigation', 'medication'"),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=False, comment="'ACCEPT', 'MODIFY', 'REJECT'"),
    sa.Column('reason', sa.Text(), nullable=True, comment="Clinician's explanation for their decision"),
    sa.Column('suggestion_context', sa.JSON(), nullable=False, comment='The exact JSON payload that was suggested'),
    sa.Column('modified_context', sa.JSON(), nullable=True, comment='The exact JSON payload after clinician modification (if decision=MODIFY)'),
    sa.Column('model_version', sa.String(length=100), server_default='1.0.0', nullable=False, comment='Version of the LLM/Embedding model used'),
    sa.Column('knowledge_version', sa.String(length=100), server_default='1.0.0', nullable=False, comment='Hash or version of the Knowledge Graph at the time'),
    sa.Column('id', sa.Uuid(), nullable=False, comment='Primary key (UUID v4, generated at INSERT)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Row insertion timestamp (UTC, server-set)'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Last modification timestamp (UTC, server-set)'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('disease_evidence',
    sa.Column('disease_id', sa.UUID(), nullable=False),
    sa.Column('evidence_id', sa.UUID(), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=True, comment='Relevance score [0.0-1.0]'),
    sa.ForeignKeyConstraint(['disease_id'], ['diseases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('disease_id', 'evidence_id'),
    sa.UniqueConstraint('disease_id', 'evidence_id', name='uq_disease_evidence')
    )
    op.create_table('medicine_contraindications',
    sa.Column('medicine_id', sa.UUID(), nullable=False),
    sa.Column('disease_id', sa.UUID(), nullable=False),
    sa.Column('severity', sa.String(length=40), nullable=True, comment="'absolute' | 'relative'"),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['disease_id'], ['diseases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('medicine_id', 'disease_id'),
    sa.UniqueConstraint('medicine_id', 'disease_id', name='uq_medicine_contraindication')
    )
    op.create_table('medicine_interactions',
    sa.Column('medicine_id_1', sa.UUID(), nullable=False),
    sa.Column('medicine_id_2', sa.UUID(), nullable=False),
    sa.Column('severity', sa.String(length=40), nullable=True, comment="'major' | 'moderate' | 'minor'"),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['medicine_id_1'], ['medicines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['medicine_id_2'], ['medicines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('medicine_id_1', 'medicine_id_2'),
    sa.UniqueConstraint('medicine_id_1', 'medicine_id_2', name='uq_medicine_interaction')
    )
    op.alter_column('clinical_notes', 'body',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_comment='Structured note sections (JSON)',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_index(op.f('ix_consent_records_patient_session_id'), table_name='consent_records')
    op.add_column('datasets', sa.Column('validation_rules', sa.JSON(), server_default='{}', nullable=False, comment='Configured quality checks (e.g., missing values thresholds)'))
    op.alter_column('datasets', 'schema',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               comment='Expected columns, types, and constraints (JSON Schema)',
               existing_comment='JSON schema defining the expected structure of the records',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    # op.create_unique_constraint('uq_disease_investigation', 'disease_investigations', ['disease_id', 'investigation_id'])
    # op.create_unique_constraint('uq_disease_medicine', 'disease_medicines', ['disease_id', 'medicine_id'])
    # op.create_unique_constraint('uq_disease_symptom', 'disease_symptoms', ['disease_id', 'symptom_id'])
    op.alter_column('doctor_posts', 'id',
               existing_type=sa.UUID(),
               comment='Primary key (UUID v4, generated at INSERT)',
               existing_nullable=False)
    op.alter_column('doctor_posts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               comment='Row insertion timestamp (UTC, server-set)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('doctor_posts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               comment='Last modification timestamp (UTC, server-set)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('evaluation_results', 'ground_truth',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_comment='Expected output from the dataset',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('evaluation_results', 'model_output',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_comment='Actual output produced by the model',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('evaluation_runs', 'metrics',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_comment='Aggregated metrics across all records (e.g. F1, precision, recall)',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('ingestion_jobs', 'validation_result',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_comment='JSON output of validation stage (errors, warnings)',
               existing_nullable=True)
    op.alter_column('ml_experiments', 'configuration',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_comment='Hyperparameters (learning rate, batch size, etc.)',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('ml_experiments', 'hardware',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_comment="Hardware topology (e.g. '8x A100 80GB')",
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('ml_experiments', 'metrics',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_comment='Recorded metrics (loss, accuracy, F1, etc.)',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.add_column('patient_sessions', sa.Column('patient_profile_id', sa.UUID(), nullable=True, comment='Link to the longitudinal patient profile'))
    op.create_index(op.f('ix_patient_sessions_patient_profile_id'), 'patient_sessions', ['patient_profile_id'], unique=False)
    op.create_foreign_key(None, 'patient_sessions', 'patient_profiles', ['patient_profile_id'], ['id'], ondelete='RESTRICT')
    op.alter_column('post_attachments', 'id',
               existing_type=sa.UUID(),
               comment='Primary key (UUID v4, generated at INSERT)',
               existing_nullable=False)
    op.alter_column('post_attachments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               comment='Row insertion timestamp (UTC, server-set)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('post_attachments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               comment='Last modification timestamp (UTC, server-set)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('post_bookmarks', 'id',
               existing_type=sa.UUID(),
               comment='Primary key (UUID v4, generated at INSERT)',
               existing_nullable=False)
    op.alter_column('post_bookmarks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               comment='Row insertion timestamp (UTC, server-set)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('post_bookmarks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               comment='Last modification timestamp (UTC, server-set)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('post_comments', 'id',
               existing_type=sa.UUID(),
               comment='Primary key (UUID v4, generated at INSERT)',
               existing_nullable=False)
    op.alter_column('post_comments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               comment='Row insertion timestamp (UTC, server-set)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('post_comments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               comment='Last modification timestamp (UTC, server-set)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('post_likes', 'id',
               existing_type=sa.UUID(),
               comment='Primary key (UUID v4, generated at INSERT)',
               existing_nullable=False)
    op.alter_column('post_likes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               comment='Row insertion timestamp (UTC, server-set)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('post_likes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               comment='Last modification timestamp (UTC, server-set)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    # op.create_unique_constraint('uq_role_permissions', 'role_permissions', ['role_id', 'permission_id'])
    op.create_index(op.f('ix_transcript_segments_transcript_id'), 'transcript_segments', ['transcript_id'], unique=False)
    op.create_index(op.f('ix_transcripts_consultation_id'), 'transcripts', ['consultation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transcripts_consultation_id'), table_name='transcripts')
    op.drop_index(op.f('ix_transcript_segments_transcript_id'), table_name='transcript_segments')
    op.drop_constraint('uq_role_permissions', 'role_permissions', type_='unique')
    op.alter_column('post_likes', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Last modification timestamp (UTC, server-set)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('post_likes', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Row insertion timestamp (UTC, server-set)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('post_likes', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Primary key (UUID v4, generated at INSERT)',
               existing_nullable=False)
    op.alter_column('post_comments', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Last modification timestamp (UTC, server-set)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('post_comments', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Row insertion timestamp (UTC, server-set)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('post_comments', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Primary key (UUID v4, generated at INSERT)',
               existing_nullable=False)
    op.alter_column('post_bookmarks', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Last modification timestamp (UTC, server-set)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('post_bookmarks', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Row insertion timestamp (UTC, server-set)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('post_bookmarks', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Primary key (UUID v4, generated at INSERT)',
               existing_nullable=False)
    op.alter_column('post_attachments', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Last modification timestamp (UTC, server-set)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('post_attachments', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Row insertion timestamp (UTC, server-set)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('post_attachments', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Primary key (UUID v4, generated at INSERT)',
               existing_nullable=False)
    op.drop_constraint(None, 'patient_sessions', type_='foreignkey')
    op.drop_index(op.f('ix_patient_sessions_patient_profile_id'), table_name='patient_sessions')
    op.drop_column('patient_sessions', 'patient_profile_id')
    op.alter_column('ml_experiments', 'metrics',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_comment='Recorded metrics (loss, accuracy, F1, etc.)',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('ml_experiments', 'hardware',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_comment="Hardware topology (e.g. '8x A100 80GB')",
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('ml_experiments', 'configuration',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_comment='Hyperparameters (learning rate, batch size, etc.)',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('ingestion_jobs', 'validation_result',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_comment='JSON output of validation stage (errors, warnings)',
               existing_nullable=True)
    op.alter_column('evaluation_runs', 'metrics',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_comment='Aggregated metrics across all records (e.g. F1, precision, recall)',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('evaluation_results', 'model_output',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_comment='Actual output produced by the model',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('evaluation_results', 'ground_truth',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_comment='Expected output from the dataset',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('doctor_posts', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Last modification timestamp (UTC, server-set)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('doctor_posts', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Row insertion timestamp (UTC, server-set)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('doctor_posts', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Primary key (UUID v4, generated at INSERT)',
               existing_nullable=False)
    op.drop_constraint('uq_disease_symptom', 'disease_symptoms', type_='unique')
    op.drop_constraint('uq_disease_medicine', 'disease_medicines', type_='unique')
    op.drop_constraint('uq_disease_investigation', 'disease_investigations', type_='unique')
    op.alter_column('datasets', 'schema',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               comment='JSON schema defining the expected structure of the records',
               existing_comment='Expected columns, types, and constraints (JSON Schema)',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_column('datasets', 'validation_rules')
    op.create_index(op.f('ix_consent_records_patient_session_id'), 'consent_records', ['patient_session_id'], unique=False)
    op.alter_column('clinical_notes', 'body',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_comment='Structured note sections (JSON)',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_table('medicine_interactions')
    op.drop_table('medicine_contraindications')
    op.drop_table('disease_evidence')
    op.drop_table('clinician_feedback')
    op.drop_index(op.f('ix_patient_profiles_tenant_id'), table_name='patient_profiles')
    op.drop_index('ix_patient_profiles_tenant', table_name='patient_profiles')
    op.drop_table('patient_profiles')
    # ### end Alembic commands ###
