"""Phase 30 Structured Clinical Note

Revision ID: f0eeb11615ba
Revises: cf99026fe3fe
Create Date: 2026-09-07 00:16:50.538015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f0eeb11615ba'
down_revision: Union[str, None] = 'cf99026fe3fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clinical_notes', sa.Column('last_edited_by_id', sa.UUID(), nullable=True, comment='Clinician who made the last edit (null if AI)'))
    op.alter_column('clinical_notes', 'body',
               existing_type=sa.TEXT(),
               server_default='{}',
               type_=postgresql.JSONB(astext_type=sa.Text()),
               postgresql_using="body::jsonb",
               comment='Structured note sections (JSON)',
               existing_comment='Note text (non-PII narrative; clinician-confirmed content only)',
               existing_nullable=False)
    op.alter_column('clinical_notes', 'version',
               existing_type=sa.INTEGER(),
               comment='Monotonically increasing version number for optimistic concurrency',
               existing_comment='Monotonically increasing version number',
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.create_foreign_key('fk_clinical_notes_last_edited_by_id_users', 'clinical_notes', 'users', ['last_edited_by_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Use safe drop to handle cases where constraint name may differ across environments
    op.execute(
        "ALTER TABLE clinical_notes DROP CONSTRAINT IF EXISTS fk_clinical_notes_last_edited_by_id_users"
    )
    op.alter_column('clinical_notes', 'version',
               existing_type=sa.INTEGER(),
               comment='Monotonically increasing version number',
               existing_comment='Monotonically increasing version number for optimistic concurrency',
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('clinical_notes', 'body',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               type_=sa.TEXT(),
               comment='Note text (non-PII narrative; clinician-confirmed content only)',
               existing_comment='Structured note sections (JSON)',
               existing_nullable=False)
    op.drop_column('clinical_notes', 'last_edited_by_id')
    # ### end Alembic commands ###
